spring:
  application:
    name: educator-service
  profiles: dev
server:
  port: 8082
eureka:
  instance:
    port: 8761
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
